version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "php"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angular",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "jquery",
    "mongo"
  ]

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "ktlint"